import { createFileRoute } from '@tanstack/react-router'
import { useState, type FormEvent } from 'react'
import { ArrowRight, Check, Clock3, Leaf, ShieldCheck, Sparkles } from 'lucide-react'

export const Route = createFileRoute('/')({ component: HomePage })
const services = [
  ['01', 'Cleaning on Your Schedule', 'Choose weekly or bi-weekly cleaning, or schedule a deep clean every three weeks or once a month.'],
  ['02', 'The Deep Clean', 'A detailed top-to-bottom refresh for first visits, seasonal resets, and homes that need extra attention.'],
  ['03', 'The Fresh Start', 'Move-in and move-out cleaning that leaves every cabinet, baseboard, and surface ready.'],
]

function HomePage() {
  const [status, setStatus] = useState<'idle'|'sending'|'success'|'error'>('idle')
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); setStatus('sending'); const form = e.currentTarget
    try {
      const response = await fetch('/contact-form.html', { method: 'POST', headers: {'Content-Type':'application/x-www-form-urlencoded'}, body: new URLSearchParams(new FormData(form) as unknown as Record<string,string>).toString() })
      if (!response.ok) throw new Error(); form.reset(); setStatus('success')
    } catch { setStatus('error') }
  }
  return <main>
    <nav className="nav wrap"><a className="brand" href="#top" aria-label="Tidy House KC home"><img className="brandLogo" src="/tidy-house-kc-logo.png" alt="Tidy House KC" width="1390" height="673"/></a><div className="links"><a href="#services">Services</a><a href="#about">Our promise</a><a href="#contact">Get a quote</a></div><a className="navCta" href="#contact">Book a clean <ArrowRight size={16}/></a></nav>
    <section className="hero wrap" id="top"><div className="heroCopy"><p className="eyebrow">— SERVING THE KANSAS CITY METRO &amp; BEYOND</p><h1>A cleaner home.<br/><em>A lighter day.</em><em>A deep clean</em><em>On your first day.</em></h1><p className="lede">Thoughtful, dependable home cleaning across the Kansas City Metro area and beyond—so you can spend your time on what matters.</p><div className="actions"><a className="button" href="#contact">Get my free quote <ArrowRight size={18}/></a><a className="under" href="#services">Explore our services</a></div><div className="trust"><span><Check/> Background-checked team</span><span><Check/> Supplies included</span></div></div>
    <section className="hero wrap" id="top"><div className="heroCopy"><p className="eyebrow">— SERVING THE KANSAS CITY METRO &amp; BEYOND</p><h1>A cleaner home.<br/><em>A lighter day.</em><em>A deep clean</em><em>On your first day.</em>em></h1><p className="lede">Thoughtful, dependable home cleaning across the Kansas City Metro area and beyond—so you can spend your time on what matters.</p><div className="actions"><a className="button" href="#contact">Get my free quote <ArrowRight size={18}/></a><a className="under" href="#services">Explore our services</a></div><div className="trust"><span><Check/> Background-checked team</span><span><Check/> Supplies included</span></div></div>
      <div className="room" aria-label="A bright, freshly cleaned living room illustration"><div className="sun"/><div className="window"/><div className="sofa"><b/><b/></div><div className="plant"><i/><i/><i/><b/></div><div className="spark">✦</div><div className="note"><Sparkles/><span><strong>Fresh-home feeling</strong>Every visit, guaranteed.</span></div></div>
    </section>
    <section className="intro wrap" id="services"><p className="kicker">HOW WE CAN HELP</p><div><h2>More ease. Less mess.</h2><p>Choose weekly, bi-weekly, every three weeks, or monthly service to fit your home and your life. Every visit follows a detailed checklist, with room for your personal priorities.</p></div></section>
    <section className="services wrap">{services.map(s=><article key={s[0]}><span>{s[0]}</span><div><h3>{s[1]}</h3><p>{s[2]}</p></div><a href="#contact" aria-label={`Ask about ${s[1]}`}><ArrowRight/></a></article>)}</section>
    <section className="promise" id="about"><div className="wrap promiseGrid"><div><p className="kicker">THE TIDY HOUSE KC PROMISE</p><h2>Care you can see.<br/>Quality you can feel.</h2><div className="icons"><span><ShieldCheck/>Fully insured</span><span><Leaf/>Thoughtful products</span><span><Clock3/>On time, every time</span></div></div><div className="quote"><b>“</b><blockquote>Walking into a truly clean home changes the whole rhythm of your week. That’s the feeling we bring to every visit.</blockquote><p>— Abigail, founder of Tidy House KC</p></div></div></section>
    <section className="contact wrap" id="contact"><div className="contactCopy"><p className="kicker">LET'S MAKE YOUR HOME SHINE</p><h2>Tell us about your space.</h2><p>Share a few details and we’ll follow up with a clear, no-pressure quote within one business day.</p>{[['01','Quick response','Hear from a real person, not a bot.'],['02','Clear pricing','No surprise fees or confusing packages.']].map(x=><div className="detail" key={x[0]}><span>{x[0]}</span><p><strong>{x[1]}</strong>{x[2]}</p></div>)}</div>
    <section className="contact wrap" id="contact"><div className="contactCopy"><p className="kicker">LET'S MAKE YOUR HOME SHINE AND SPARKLE</p><h2>Tell us about your space.</h2><p>Share a few details and we’ll follow up with a clear, no-pressure quote within one business day.</p>{[['01','Quick response','Hear from a real person, not a bot.'],['02','Clear pricing','No surprise fees or confusing packages.']].map(x=><div className="detail" key={x[0]}><span>{x[0]}</span><p><strong>{x[1]}</strong>{x[2]}</p></div>)}</div>
      <div className="formCard">{status==='success'?<div className="success"><i><Check/></i><h3>Your lighter day starts here.</h3><p>Thanks for reaching out. We’ll be in touch within one business day with your personalized quote.</p><button className="under" onClick={()=>setStatus('idle')}>Send another request</button></div>:<form name="cleaning-quote" method="POST" data-netlify="true" netlify-honeypot="bot-field" onSubmit={submit}><input type="hidden" name="form-name" value="cleaning-quote"/><p className="bot"><label>Leave empty<input name="bot-field"/></label></p><div className="fieldRow"><label>Your name<input name="name" placeholder="Full name" required/></label><label>Email address<input name="email" type="email" placeholder="you@example.com" required/></label></div><div className="fieldRow"><label>Phone number<input name="phone" type="tel" placeholder="(555) 123-4567" required/></label><label>Service needed<select name="service" defaultValue="" required><option value="" disabled>Choose a service</option><option>Weekly cleaning</option><option>Bi-weekly cleaning</option><option>Deep clean every three weeks</option><option>Monthly deep clean</option><option>One-time deep cleaning</option><option>Move-in / move-out</option><option>Not sure yet</option></select></label></div><label>Tell us a little about your home<textarea name="message" rows={4} placeholder="Bedrooms, bathrooms, and anything else we should know..." required/></label><button className="button submit" disabled={status==='sending'}>{status==='sending'?'Sending…':'Request my free quote'} <ArrowRight/></button>{status==='error'&&<p className="error" role="alert">Something went wrong. Please try again.</p>}<p className="privacy">No spam. Just a helpful quote from our team.</p></form>}</div>
    </section>
    <footer><div className="wrap footerTop"><a className="brand" href="#top" aria-label="Tidy House KC home"><img className="brandLogo" src="/tidy-house-kc-logo.png" alt="Tidy House KC" width="1390" height="673"/></a><p>More time for living. Less time cleaning.</p><div><a href="#services">Services</a><a href="#contact">Contact</a></div></div><div className="wrap copyright">© {new Date().getFullYear()} Tidy House KC Home Cleaning Co.<span>Serving the Kansas City Metro area and beyond.</span></div></footer>
  </main>
}
